# Generated by Django 3.0.3 on 2020-10-31 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_container', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
    ]
