# Generated by Django 3.0.3 on 2020-10-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_container', '0002_remove_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listcontainer',
            name='title',
            field=models.CharField(error_messages={'unique': 'This title is not unique, please try again'}, help_text='Must be a unique title', max_length=100, unique=True),
        ),
    ]
