# Generated by Django 3.0.3 on 2020-11-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_container', '0004_listcontainer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
