# Generated by Django 3.0.3 on 2020-11-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_container', '0005_task_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='details',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
